from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "workshop" / "ruang_irama.workshop"
VALIDATOR = ROOT / "tools" / "validate_workshop.py"
TESTS = ROOT / "tests" / "test_validate_workshop.py"
README = ROOT / "README.md"
PROJECT = ROOT / "docs" / "PROGETTO.md"
TESTDOC = ROOT / "docs" / "TEST.md"
VALIDATION = ROOT / "docs" / "VALIDAZIONE.md"
VERSION = ROOT / "VERSION"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one occurrence, found {count}")
    return text.replace(old, new, 1)


def matching_brace(text: str, opening: int) -> int:
    depth = 1
    in_string = False
    escaped = False
    for i in range(opening + 1, len(text)):
        ch = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
    raise RuntimeError("unbalanced brace")


def rule_span(text: str, prefix: str) -> tuple[int, int]:
    start = text.index(f'rule("{prefix}')
    opening = text.index("{", start)
    end = matching_brace(text, opening) + 1
    return start, end


def actions_body(rule_text: str) -> str:
    marker = "\tactions\n\t{"
    at = rule_text.index(marker)
    opening = rule_text.index("{", at)
    closing = matching_brace(rule_text, opening)
    return rule_text[opening + 1:closing]


def git_blob_sha(path: Path) -> str:
    data = path.read_bytes().replace(b"\r\n", b"\n")
    payload = b"blob " + str(len(data)).encode("ascii") + b"\0" + data
    return hashlib.sha1(payload).hexdigest()


source = SOURCE.read_text(encoding="utf-8")

# New reusable lifecycle cleanup, used both for a real leave and for the
# Player Joined event generated by a team switch.
source = replace_once(
    source,
    "\t26: HitungPilihan\n}",
    "\t26: HitungPilihan\n\t27: BersihkanPemain\n}",
    "cleanup subroutine declaration",
)

# Player Joined Match can fire again when moving team. If the player is already
# in the human roster, remove the old registration first, then initialize from 0.
old_join = '''rule("01 - Pemain Masuk: Mulai jam nongkrong")
{
\tevent
\t{
\t\tPlayer Joined Match;
\t\tAll;
\t\tAll;
\t}

\tconditions
\t{
\t\tIs Dummy Bot(Event Player) == False;
\t}

\tactions
\t{
\t\tCall Subroutine(SiapkanPemain);
\t}
}'''
new_join = '''rule("01 - Pemain Masuk atau Pindah Tim: Bersihkan lalu siapkan ulang")
{
\tevent
\t{
\t\tPlayer Joined Match;
\t\tAll;
\t\tAll;
\t}

\tconditions
\t{
\t\tIs Dummy Bot(Event Player) == False;
\t}

\tactions
\t{
\t\tIf(Array Contains(Global.PemainManusia, Event Player));
\t\t\tCall Subroutine(BersihkanPemain);
\t\tEnd;
\t\tCall Subroutine(SiapkanPemain);
\t}
}'''
source = replace_once(source, old_join, new_join, "team-switch aware join")

# Absolute last guard: a human entity can never be appended twice, even if a
# future event ordering changes.
source = replace_once(
    source,
    "\t\tAbort If(Entity Exists(Event Player) == False);\n\t\tAbort If(Count Of(Global.SlotHUDTersedia) == 0);",
    "\t\tAbort If(Entity Exists(Event Player) == False);\n\t\tAbort If(Array Contains(Global.PemainManusia, Event Player));\n\t\tAbort If(Count Of(Global.SlotHUDTersedia) == 0);",
    "duplicate roster append guard",
)

# A vote is a scalar choice. Make replacement explicit: clear A, assign B, then
# recount exactly once. This also documents the required semantics in Workshop.
source = replace_once(
    source,
    "\t\t\t\t\tEvent Player.PemainDipilih = Global.PemainManusia[Event Player.KursorPilihan];\n\t\t\t\t\tCall Subroutine(HitungPilihan);",
    "\t\t\t\t\tEvent Player.PemainDipilih = Null;\n\t\t\t\t\tEvent Player.PemainDipilih = Global.PemainManusia[Event Player.KursorPilihan];\n\t\t\t\t\tCall Subroutine(HitungPilihan);",
    "explicit vote replacement",
)

# Extract the existing proven leave cleanup and turn it into a reusable subroutine.
leave_start, leave_end = rule_span(source, "04 - Pemain Keluar:")
leave_rule = source[leave_start:leave_end]
old_cleanup = actions_body(leave_rule)

# Stop Camera is now universal and executed before roster removal, so remove the
# old conditional duplicate from the extracted body.
old_cleanup = old_cleanup.replace("\n\t\t\tStop Camera(Event Player);", "", 1)

fresh_runtime_reset = '''
\t\t"Pulihkan keadaan runtime sebelum data roster dihapus; ini membuat pindah tim setara dengan keluar lalu masuk lagi."
\t\tStop Camera(Event Player);
\t\tAllow Button(Event Player, Button(Melee));
\t\tAllow Button(Event Player, Button(Jump));
\t\tAllow Button(Event Player, Button(Crouch));
\t\tAllow Button(Event Player, Button(Primary Fire));
\t\tAllow Button(Event Player, Button(Secondary Fire));
\t\tAllow Button(Event Player, Button(Interact));
\t\tAllow Button(Event Player, Button(Reload));
\t\tAllow Button(Event Player, Button(Ability 1));
\t\tAllow Button(Event Player, Button(Ability 2));
\t\tAllow Button(Event Player, Button(Ultimate));
\t\tSet Primary Fire Enabled(Event Player, True);
\t\tSet Secondary Fire Enabled(Event Player, True);
\t\tSet Ability 1 Enabled(Event Player, True);
\t\tSet Ability 2 Enabled(Event Player, True);
\t\tSet Ultimate Ability Enabled(Event Player, True);
\t\tSet Melee Enabled(Event Player, True);
\t\tSet Damage Dealt(Event Player, 100);
\t\tSet Healing Dealt(Event Player, 100);
\t\tSet Knockback Dealt(Event Player, 100);
\t\tSet Damage Received(Event Player, 100);
\t\tSet Move Speed(Event Player, 100);
\t\tClear Status(Event Player, Unkillable);
\t\tStop Modifying Hero Voice Lines(Event Player);
\t\tEnable Game Mode HUD(Event Player);
\t\tEnable Game Mode In-World UI(Event Player);
\t\tEvent Player.PemainDipilih = Null;
\t\tEvent Player.JumlahSuara = 0;
\t\tEvent Player.SudahSiap = False;
\t\tEvent Player.SudahDiperiksa = False;
\t\tEvent Player.Manusia = False;
'''
cleanup_actions = fresh_runtime_reset + old_cleanup
cleanup_rule = '''rule("93c - Subrutin: Bersihkan pemain saat keluar atau pindah tim")
{
\tevent
\t{
\t\tSubroutine;
\t\tBersihkanPemain;
\t}

\tactions
\t{''' + cleanup_actions + '''\n\t}
}

'''

# Real leave now delegates to the exact same cleanup used on team-switch rejoin.
new_leave = '''rule("04 - Pemain Keluar: Bersihkan pendaftaran dan semua referensi")
{
\tevent
\t{
\t\tPlayer Left Match;
\t\tAll;
\t\tAll;
\t}

\tactions
\t{
\t\tCall Subroutine(BersihkanPemain);
\t}
}'''
source = source[:leave_start] + new_leave + source[leave_end:]
source = replace_once(
    source,
    'rule("94 - Subrutin: Siapkan pemain dari ujung rambut sampai variabel")',
    cleanup_rule + 'rule("94 - Subrutin: Siapkan pemain dari ujung rambut sampai variabel")',
    "insert reusable cleanup rule",
)

SOURCE.write_text(source, encoding="utf-8")

# ---------------------------------------------------------------------------
# Validator: reusable cleanup + team switch + one-vote semantics.
# ---------------------------------------------------------------------------
validator = VALIDATOR.read_text(encoding="utf-8")
validator = validator.replace('CURRENT_VERSION = "0.6.1"', 'CURRENT_VERSION = "0.6.2"')
validator = validator.replace('versione 0.6.1', 'versione 0.6.2')

# check_cleanup_and_revenge: inspect the reusable cleanup rather than the thin
# Player Left event wrapper.
old_cleanup_validator = '''    leave_rules = [rule for rule in rules if code_contains(rule.body, "Player Left Match;")]
    checks.equal(len(leave_rules), 1, "regole Player Left Match")
    if leave_rules:
        leave = mask_strings(leave_rules[0].body)
        capture_at = leave.find("Global.PemainPembersihan = Event Player;")
        index_at = leave.find(
            "Global.IndeksKeluar = Index Of Array Value(Global.PemainManusia, Event Player);"
        )
        checks.require(
            0 <= capture_at < index_at,
            "cleanup uscita non cattura subito l'identità del giocatore",
        )
        removal_at = leave.find("Modify Global Variable(PemainManusia, Remove From Array By Index")
        checks.require(removal_at >= 0, "cleanup uscita non rimuove il giocatore dal roster")
        if removal_at >= 0:
            checks.require(
                "Event Player." not in leave[removal_at:],
                "cleanup uscita legge variabili dell'entità dopo averla rimossa dal roster",
            )
        for collection in (
            "PemainManusia", "HudKiriPemain", "HudKananPemain", "HudMenuPemain",
            "TeksDuniaPemain", "TeksDiriPemain", "SlotHUDPemain",
        ):
            checks.require(
                re.search(
                    rf"Modify Global Variable\\s*\\(\\s*{collection}\\s*,\\s*Remove From Array By Index",
                    leave,
                )
                is not None,
                f"cleanup uscita non allineato per Global.{collection}",
            )
        checks.require(
            "Sorted Array(Append To Array(Global.SlotHUDTersedia, Global.SlotHUDPemain[Global.IndeksKeluar])"
            in leave,
            "cleanup uscita non libera lo slot HUD",
        )
        checks.require("For Global Variable" in leave, "cleanup uscita non visita tutti i superstiti")
        checks.require("BalasDendam" in leave, "cleanup uscita non ripulisce i ledger BalasDendam")
        checks.require("Stop Camera" in leave, "cleanup uscita non ferma le camere puntate all'uscente")
'''
new_cleanup_validator = '''    leave_rules = [rule for rule in rules if code_contains(rule.body, "Player Left Match;")]
    checks.equal(len(leave_rules), 1, "regole Player Left Match")
    cleanup_rules = rules_containing(rules, "Subroutine;", "BersihkanPemain;")
    checks.equal(len(cleanup_rules), 1, "subroutine lifecycle BersihkanPemain")
    if leave_rules:
        checks.require(
            code_contains(leave_rules[0].body, "Call Subroutine(BersihkanPemain);"),
            "Player Left non delega al cleanup comune",
        )
    if cleanup_rules:
        leave = mask_strings(cleanup_rules[0].body)
        capture_at = leave.find("Global.PemainPembersihan = Event Player;")
        index_at = leave.find(
            "Global.IndeksKeluar = Index Of Array Value(Global.PemainManusia, Event Player);"
        )
        checks.require(
            0 <= capture_at < index_at,
            "cleanup uscita non cattura subito l'identità del giocatore",
        )
        removal_at = leave.find("Modify Global Variable(PemainManusia, Remove From Array By Index")
        checks.require(removal_at >= 0, "cleanup uscita non rimuove il giocatore dal roster")
        if removal_at >= 0:
            checks.require(
                "Event Player." not in leave[removal_at:],
                "cleanup uscita legge variabili dell'entità dopo averla rimossa dal roster",
            )
        for collection in (
            "PemainManusia", "HudKiriPemain", "HudKananPemain", "HudMenuPemain",
            "TeksDuniaPemain", "TeksDiriPemain", "SlotHUDPemain",
        ):
            checks.require(
                re.search(
                    rf"Modify Global Variable\\s*\\(\\s*{collection}\\s*,\\s*Remove From Array By Index",
                    leave,
                )
                is not None,
                f"cleanup uscita non allineato per Global.{collection}",
            )
        checks.require(
            "Sorted Array(Append To Array(Global.SlotHUDTersedia, Global.SlotHUDPemain[Global.IndeksKeluar])"
            in leave,
            "cleanup uscita non libera lo slot HUD",
        )
        checks.require("For Global Variable" in leave, "cleanup uscita non visita tutti i superstiti")
        checks.require("BalasDendam" in leave, "cleanup uscita non ripulisce i ledger BalasDendam")
        checks.require("Stop Camera(Event Player);" in leave, "cleanup comune non ferma la camera del player")
'''
validator = replace_once(validator, old_cleanup_validator, new_cleanup_validator, "validator reusable cleanup")

# Teleport target cleanup now lives in BersihkanPemain.
old_tele_leave = '''    leave_rules = [rule for rule in rules if code_contains(rule.body, "Player Left Match;")]
    if leave_rules:
        checks.require(
            code_contains(
                leave_rules[0].body,
                "TargetTeleportasiTerkunci == Global.PemainPembersihan",
                "TargetTeleportasiTerkunci, Null",
            ),
            "Teleport: uscita del target non annulla l'identità bloccata",
        )
'''
new_tele_leave = '''    cleanup_rules = rules_containing(rules, "Subroutine;", "BersihkanPemain;")
    if cleanup_rules:
        checks.require(
            code_contains(
                cleanup_rules[0].body,
                "TargetTeleportasiTerkunci == Global.PemainPembersihan",
                "TargetTeleportasiTerkunci, Null",
            ),
            "Teleport: uscita/cambio team del target non annulla l'identità bloccata",
        )
'''
validator = replace_once(validator, old_tele_leave, new_tele_leave, "validator teleport cleanup subroutine")

# Lifecycle audit now explicitly certifies team-switch cleanup and duplicate guard.
old_lifecycle = '''    join = [rule for rule in rules if code_contains(rule.body, "Player Joined Match;", "Call Subroutine(SiapkanPemain);")]
    fallback = [rule for rule in rules if code_contains(rule.body, "Ongoing - Each Player;", "Event Player.SudahSiap == False;", "Call Subroutine(SiapkanPemain);")]
    checks.equal(len(join), 1, "audit lifecycle: init Player Joined")
    checks.equal(len(fallback), 1, "audit lifecycle: init player già presenti")

    leave = [rule for rule in rules if code_contains(rule.body, "Player Left Match;")]
    checks.equal(len(leave), 1, "audit lifecycle: un solo cleanup Player Left")
    if leave:
        body = mask_strings(leave[0].body)
        capture = body.find("Global.PemainPembersihan = Event Player;")
        checks.require(capture >= 0, "audit lifecycle: leave non cattura identità")
        for token in (
            "Destroy In-World Text(Event Player.TeksKartuNasib);",
            "Destroy In-World Text(Event Player.TeksKartuNasibKanan);",
            "Destroy Icon(Event Player.IkonKartuNasib);",
            "Destroy Icon(Event Player.IkonKartuNasibHijau);",
        ):
            position = body.find(token)
            checks.require(0 <= position < capture, f"audit lifecycle: cleanup Nasib non universale prima del lookup: {token}")
        for array_name in (
            "HudKiriPemain", "HudKananPemain", "HudMenuPemain", "TeksDuniaPemain",
            "TeksDiriPemain", "SlotHUDPemain", "PemainManusia",
        ):
            checks.require(
                f"Modify Global Variable({array_name}, Remove From Array By Index, Global.IndeksKeluar);" in body,
                f"audit lifecycle: array parallelo non ripulito al leave: {array_name}",
            )
        for token in (
            "PemainDipilih == Global.PemainPembersihan",
            "TargetKamera == Global.PemainPembersihan",
            "TargetInspeksi == Global.PemainPembersihan",
            "TargetTeleportasiTerkunci == Global.PemainPembersihan",
            "TargetBalasDendamDipilih == Global.PemainPembersihan",
            "TargetBalasDendamTerkunci == Global.PemainPembersihan",
        ):
            checks.require(token in body, f"audit lifecycle: riferimento stale non ripulito: {token}")
'''
new_lifecycle = '''    join = [rule for rule in rules if code_contains(rule.body, "Player Joined Match;", "Call Subroutine(SiapkanPemain);")]
    fallback = [rule for rule in rules if code_contains(rule.body, "Ongoing - Each Player;", "Event Player.SudahSiap == False;", "Call Subroutine(SiapkanPemain);")]
    checks.equal(len(join), 1, "audit lifecycle: init Player Joined")
    checks.equal(len(fallback), 1, "audit lifecycle: init player già presenti")
    if join:
        body = mask_strings(join[0].body)
        duplicate_at = body.find("If(Array Contains(Global.PemainManusia, Event Player));")
        cleanup_at = body.find("Call Subroutine(BersihkanPemain);", duplicate_at)
        setup_at = body.find("Call Subroutine(SiapkanPemain);", cleanup_at)
        checks.require(
            0 <= duplicate_at < cleanup_at < setup_at,
            "audit lifecycle: cambio team non esegue cleanup prima della nuova inizializzazione",
        )

    classification = [rule for rule in rules if rule.name.startswith("02 - Pemain:")]
    checks.equal(len(classification), 1, "audit lifecycle: una sola registrazione roster")
    if classification:
        body = mask_strings(classification[0].body)
        guard = body.find("Abort If(Array Contains(Global.PemainManusia, Event Player));")
        append = body.find("Global.PemainManusia = Append To Array(Global.PemainManusia, Event Player);")
        checks.require(0 <= guard < append, "audit lifecycle: append roster senza guardia anti-duplicato")

    leave = [rule for rule in rules if code_contains(rule.body, "Player Left Match;")]
    cleanup = rules_containing(rules, "Subroutine;", "BersihkanPemain;")
    checks.equal(len(leave), 1, "audit lifecycle: un solo evento Player Left")
    checks.equal(len(cleanup), 1, "audit lifecycle: un solo cleanup riutilizzabile")
    if leave:
        checks.require(code_contains(leave[0].body, "Call Subroutine(BersihkanPemain);"), "audit lifecycle: Player Left non usa cleanup comune")
    if cleanup:
        body = mask_strings(cleanup[0].body)
        capture = body.find("Global.PemainPembersihan = Event Player;")
        checks.require(capture >= 0, "audit lifecycle: cleanup non cattura identità")
        for token in (
            "Destroy In-World Text(Event Player.TeksKartuNasib);",
            "Destroy In-World Text(Event Player.TeksKartuNasibKanan);",
            "Destroy Icon(Event Player.IkonKartuNasib);",
            "Destroy Icon(Event Player.IkonKartuNasibHijau);",
        ):
            position = body.find(token)
            checks.require(0 <= position < capture, f"audit lifecycle: cleanup Nasib non universale prima del lookup: {token}")
        for array_name in (
            "HudKiriPemain", "HudKananPemain", "HudMenuPemain", "TeksDuniaPemain",
            "TeksDiriPemain", "SlotHUDPemain", "PemainManusia",
        ):
            checks.require(
                f"Modify Global Variable({array_name}, Remove From Array By Index, Global.IndeksKeluar);" in body,
                f"audit lifecycle: array parallelo non ripulito: {array_name}",
            )
        for token in (
            "PemainDipilih == Global.PemainPembersihan",
            "TargetKamera == Global.PemainPembersihan",
            "TargetInspeksi == Global.PemainPembersihan",
            "TargetTeleportasiTerkunci == Global.PemainPembersihan",
            "TargetBalasDendamDipilih == Global.PemainPembersihan",
            "TargetBalasDendamTerkunci == Global.PemainPembersihan",
        ):
            checks.require(token in body, f"audit lifecycle: riferimento stale non ripulito: {token}")
        for token in (
            "Event Player.PemainDipilih = Null;",
            "Event Player.JumlahSuara = 0;",
            "Event Player.SudahSiap = False;",
            "Event Player.Manusia = False;",
            "Clear Status(Event Player, Unkillable);",
            "Set Damage Received(Event Player, 100);",
            "Allow Button(Event Player, Button(Interact));",
        ):
            checks.require(token in body, f"audit lifecycle: reset fresco incompleto: {token}")
'''
validator = replace_once(validator, old_lifecycle, new_lifecycle, "validator team-switch lifecycle")

# Unkillable leave cleanup is now in the shared subroutine.
validator = replace_once(
    validator,
    '''    leave = [r for r in rules if code_contains(r.body, "Player Left Match;")]
    checks.require(bool(leave) and "Destroy Icon(Event Player.IkonKebal);" in mask_strings(leave[0].body), "Unkillable Halo cleanup leave assente")''',
    '''    cleanup = rules_containing(rules, "Subroutine;", "BersihkanPemain;")
    checks.require(bool(cleanup) and "Destroy Icon(Event Player.IkonKebal);" in mask_strings(cleanup[0].body), "Unkillable icon cleanup leave/team-switch assente")''',
    "validator unkillable shared cleanup",
)

# Vote: certify one scalar vote, explicit A->Null->B replacement, and cleanup on
# both leave and team switch.
old_vote_tail = '''    if handlers:
        body = mask_strings(handlers[0].body)
        checks.require("Event Player.PemainDipilih = Global.PemainManusia[Event Player.KursorPilihan];" in body and "Call Subroutine(HitungPilihan);" in body, "Vote: applicazione voto incompleta")
    checks.require("CHILL STAR:" in source and "BINTANG CHILL:" in source and "ดาวสายชิล:" in source, "Vote: HUD Chill Star assente")
'''
new_vote_tail = '''    if handlers:
        body = mask_strings(handlers[0].body)
        guard = body.find("If(Event Player.PemainDipilih != Global.PemainManusia[Event Player.KursorPilihan]);")
        clear = body.find("Event Player.PemainDipilih = Null;", guard)
        assign = body.find("Event Player.PemainDipilih = Global.PemainManusia[Event Player.KursorPilihan];", clear)
        recount = body.find("Call Subroutine(HitungPilihan);", assign)
        checks.require(0 <= guard < clear < assign < recount, "Vote: cambio scelta non elimina il voto precedente prima del nuovo")
        checks.require("Append To Array(Event Player.PemainDipilih" not in body, "Vote: scelta non deve mai diventare un array di voti")
    cleanup = rules_containing(rules, "Subroutine;", "BersihkanPemain;")
    if cleanup:
        body = mask_strings(cleanup[0].body)
        checks.require("Event Player.PemainDipilih = Null;" in body, "Vote: voto uscente non azzerato su leave/team-switch")
        checks.require("PemainDipilih == Global.PemainPembersihan" in body, "Vote: voti ricevuti dal player uscente non azzerati")
        checks.require("Call Subroutine(HitungPilihan);" in body, "Vote: conteggi non ricalcolati dopo leave/team-switch")
    checks.require("CHILL STAR:" in source and "BINTANG CHILL:" in source and "ดาวสายชิล:" in source, "Vote: HUD Chill Star assente")
'''
validator = replace_once(validator, old_vote_tail, new_vote_tail, "validator one active vote")
validator = replace_once(
    validator,
    '''    leave = [r for r in rules if code_contains(r.body, "Player Left Match;")]
    checks.require(bool(leave) and "PemainDipilih == Global.PemainPembersihan" in mask_strings(leave[0].body), "Vote: cleanup leave assente")''',
    '''    cleanup = rules_containing(rules, "Subroutine;", "BersihkanPemain;")
    checks.require(bool(cleanup) and "PemainDipilih == Global.PemainPembersihan" in mask_strings(cleanup[0].body), "Vote: cleanup leave/team-switch assente")''',
    "validator vote cleanup location",
)

# Static subroutine inventory should include cleanup exactly once.
validator = replace_once(
    validator,
    'for sub in ("GambarUtama", "GambarMusik", "GambarKamera", "GambarWarna", "GambarBahasa", "GambarBalasDendam", "GambarTeleportasi", "GambarKebal", "GambarSuara", "GambarIkon"):',
    'for sub in ("GambarUtama", "GambarMusik", "GambarKamera", "GambarWarna", "GambarBahasa", "GambarBalasDendam", "GambarTeleportasi", "GambarKebal", "GambarSuara", "GambarIkon", "BersihkanPemain"):',
    "validator cleanup unique subroutine",
)

VALIDATOR.write_text(validator, encoding="utf-8")

# ---------------------------------------------------------------------------
# Regression tests: 26 -> 28.
# ---------------------------------------------------------------------------
tests = TESTS.read_text(encoding="utf-8")
tests = tests.replace("0.6.1", "0.6.2")
marker = '\n\nif __name__ == "__main__":\n    unittest.main()'
extra = r'''

    def test_team_rejoin_must_cleanup_before_setup(self) -> None:
        mutated = self.source.replace(
            "\t\tIf(Array Contains(Global.PemainManusia, Event Player));\n\t\t\tCall Subroutine(BersihkanPemain);\n\t\tEnd;\n\t\tCall Subroutine(SiapkanPemain);",
            "\t\tCall Subroutine(SiapkanPemain);",
            1,
        )
        self.assertNotEqual(mutated, self.source)
        _, player_names, _ = validator.declaration_tables(mutated)
        checks = validator.Checks()
        validator.check_lifecycle_hygiene(checks, mutated, self.rules(mutated), player_names)
        self.assertTrue(any("cambio team" in error for error in checks.errors), checks.errors)

    def test_vote_change_must_clear_previous_choice(self) -> None:
        mutated = self.source.replace(
            "\t\t\t\t\tEvent Player.PemainDipilih = Null;\n\t\t\t\t\tEvent Player.PemainDipilih = Global.PemainManusia[Event Player.KursorPilihan];",
            "\t\t\t\t\tEvent Player.PemainDipilih = Global.PemainManusia[Event Player.KursorPilihan];",
            1,
        )
        self.assertNotEqual(mutated, self.source)
        _, _, subroutines = validator.declaration_tables(mutated)
        checks = validator.Checks()
        validator.check_vote_menu(checks, mutated, self.rules(mutated), subroutines)
        self.assertTrue(any("voto precedente" in error for error in checks.errors), checks.errors)
'''
if extra.strip() not in tests:
    if marker not in tests:
        raise RuntimeError("test insertion marker missing")
    tests = tests.replace(marker, extra + marker, 1)
TESTS.write_text(tests, encoding="utf-8")

# ---------------------------------------------------------------------------
# Version/docs.
# ---------------------------------------------------------------------------
VERSION.write_text("0.6.2\n", encoding="utf-8")
for path in (README, PROJECT, TESTDOC, VALIDATION):
    text = path.read_text(encoding="utf-8").replace("0.6.1", "0.6.2")
    text = text.replace("26 unit test", "28 unit test").replace("Ran 26 tests", "Ran 28 tests")
    path.write_text(text, encoding="utf-8")

readme = README.read_text(encoding="utf-8")
if "Team switch 0.6.2" not in readme:
    readme += '''\n\n### Team switch 0.6.2\n\n`Player Joined Match` può essere generato anche da un cambio squadra. Se il player è già presente nel roster, `BersihkanPemain` esegue lo stesso cleanup del Player Left prima di `SiapkanPemain`: HUD, slot, Menu 10, camera, input, Unkillable, riferimenti e voto vengono azzerati. La regola di registrazione ha inoltre una guardia `Array Contains(Global.PemainManusia, Event Player)` che impedisce un secondo append della stessa entità. Ogni player mantiene un solo `PemainDipilih`; cambiando scelta il valore precedente viene prima impostato a `Null`, poi viene assegnato il nuovo target e `HitungPilihan` ricalcola i totali.\n'''
README.write_text(readme, encoding="utf-8")

project = PROJECT.read_text(encoding="utf-8")
if "## Cambio squadra e voto singolo 0.6.2" not in project:
    project += '''\n\n## Cambio squadra e voto singolo 0.6.2\n\nUn cambio Team viene trattato come un'uscita e un nuovo ingresso logico. `01 - Pemain Masuk atau Pindah Tim` controlla se l'entità è già in `Global.PemainManusia`; in tal caso chiama `BersihkanPemain`, che usa lo stesso percorso del vero `Player Left Match`, e solo dopo richiama `SiapkanPemain`. Il cleanup rimuove il vecchio HUD e tutti gli array paralleli, restituisce lo slot HUD, azzera il voto uscente, annulla i voti degli altri diretti al player, pulisce i riferimenti Camera/Revenge/Teleport/Inspection, ripristina input e modificatori e ricalcola i voti. La registrazione umana contiene anche una seconda guardia anti-duplicato prima dell'allocazione HUD.\n\nIl voto resta una singola variabile `PemainDipilih`, non un array. Scegliendo un player diverso, l'handler esegue esplicitamente `PemainDipilih = Null`, assegna il nuovo player e poi chiama `HitungPilihan`; quindi il voto precedente viene sempre sottratto e il nuovo aggiunto nello stesso aggiornamento.\n'''
PROJECT.write_text(project, encoding="utf-8")

testdoc = TESTDOC.read_text(encoding="utf-8")
if "## Cambio squadra" not in testdoc:
    testdoc += '''\n\n## Cambio squadra\n\n- Con un player già registrato, passare Team 1 → Team 2 → Team 1 più volte. Deve esistere sempre una sola riga roster per quel player e un solo elemento corrispondente in `Global.PemainManusia`.\n- Se il player aveva votato A, dopo il cambio squadra il suo voto deve essere `NONE/BELUM ADA/ยังไม่ได้โหวต` e il totale di A deve diminuire di uno.\n- Anche tutti i voti ricevuti dal player che cambia squadra devono essere eliminati, come in un vero leave/rejoin.\n- Menu, Crouch Teleport, camera, Unkillable, voce, cursori e HUD temporanei devono ripartire dai valori iniziali.\n- Votare A e poi B senza cambiare Team: A deve perdere immediatamente un voto e B deve guadagnarne uno; il votante non può contribuire a due target contemporaneamente.\n'''
TESTDOC.write_text(testdoc, encoding="utf-8")

validation = VALIDATION.read_text(encoding="utf-8")
blob = git_blob_sha(SOURCE)
validation = re.sub(
    r"(Blob Git del sorgente Workshop validato:\s*```text\s*)[0-9a-f]{40}(\s*```)",
    rf"\g<1>{blob}\g<2>",
    validation,
    count=1,
)
validation = validation.replace("26 unit test", "28 unit test").replace("Ran 26 tests", "Ran 28 tests")
if "team-switch" not in validation.lower():
    validation = validation.replace(
        "## Audit 0.6.2\n",
        "## Audit 0.6.2\n\n- team-switch trattato come leave + fresh join con cleanup riutilizzabile e guardia anti-duplicato roster;\n- voto singolo certificato: cambio scelta azzera il target precedente prima di assegnare il nuovo;\n",
        1,
    )
VALIDATION.write_text(validation, encoding="utf-8")
